### ISSUE TITLE
GPIO test fails

### ISSUE THREAD

**Issue by andypiper** [paperdink/paperd_ink_test#1]
By default there's nothing attached to the GPIO, so the sample will hang when it reaches this point in the code. Suggest commenting this out and documenting how to use it.

**Comment by andypiper** [comment]
(not only that, but the GPIO pin holes are soldered closed on my paperd.ink Classic, as supplied, so not clear how this is supposed to work?)

**Comment by rgujju** [comment]
The gpio test checks for the I2C communication between ESP32 and the I/O expander. So it does not hang.
There are no holes for the GPIO. It is a placeholder for surface mount headers or direct wiring. Like these:
![image](https://user-images.githubusercontent.com/10092220/212585127-d8906c64-c969-4fc7-a623-49c7265bc316.png)

**Comment by rgujju** [comment]
The I2C seems to work only with ESP32 core version 1.0.4. Will have to dig deeper to see why that is the case.

**Comment by andypiper** [comment]
Ah, good to know, thanks for looking into it. In the meantime, if anyone is having this issue then just commenting the test is a quick way to move past to the next step in the demo.

**Comment by rgujju** [comment]
Fixed by #3
